import { Inter } from "next/font/google";
import Navigation from "@/app/ui/navbar/navbar";
import Footer from "@/app/ui/footer/footer";
import "./globals.css";
import "flowbite";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "The physio rehab practice",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <script
          src="https://static.elfsight.com/platform/platform.js"
          data-use-service-core
          defer
        ></script>
      </head>
      <body className={inter.className}>
        {/* <Navigation /> */}
        {children}
        <Footer />
      </body>
    </html>
  );
}
